/* soapClient.c
   Generated by gSOAP 2.8.3 from addclient.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.3 2012-03-02 00:35:24 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ReceiveTaskList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__data *data, struct ns1__ReceiveTaskListResponse *_param_1)
{	struct ns1__ReceiveTaskList soap_tmp_ns1__ReceiveTaskList;
	if (!soap_endpoint)
		soap_endpoint = "http://10.42.43.41:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ReceiveTaskList.data = data;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__ReceiveTaskList(soap, &soap_tmp_ns1__ReceiveTaskList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ReceiveTaskList(soap, &soap_tmp_ns1__ReceiveTaskList, "ns1:ReceiveTaskList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ReceiveTaskList(soap, &soap_tmp_ns1__ReceiveTaskList, "ns1:ReceiveTaskList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__ReceiveTaskListResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__ReceiveTaskListResponse(soap, _param_1, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__TaskSolve(struct soap *soap, const char *soap_endpoint, const char *soap_action, int taskId, struct ns1__soap_string *task, struct ns1__TaskSolveResponse *_param_2)
{	struct ns1__TaskSolve soap_tmp_ns1__TaskSolve;
	if (!soap_endpoint)
		soap_endpoint = "http://10.42.43.41:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__TaskSolve.taskId = taskId;
	soap_tmp_ns1__TaskSolve.task = task;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__TaskSolve(soap, &soap_tmp_ns1__TaskSolve);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__TaskSolve(soap, &soap_tmp_ns1__TaskSolve, "ns1:TaskSolve", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__TaskSolve(soap, &soap_tmp_ns1__TaskSolve, "ns1:TaskSolve", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns1__TaskSolveResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__TaskSolveResponse(soap, _param_2, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__isBusy(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *flag)
{	struct ns1__isBusy soap_tmp_ns1__isBusy;
	struct ns1__isBusyResponse *soap_tmp_ns1__isBusyResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://10.42.43.41:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__isBusy(soap, &soap_tmp_ns1__isBusy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__isBusy(soap, &soap_tmp_ns1__isBusy, "ns1:isBusy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__isBusy(soap, &soap_tmp_ns1__isBusy, "ns1:isBusy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!flag)
		return soap_closesock(soap);
	soap_default_int(soap, flag);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__isBusyResponse = soap_get_ns1__isBusyResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (flag && soap_tmp_ns1__isBusyResponse->flag)
		*flag = *soap_tmp_ns1__isBusyResponse->flag;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__ReceiveTaskList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__data *data, struct ns2__ReceiveTaskListResponse *_param_3)
{	struct ns2__ReceiveTaskList soap_tmp_ns2__ReceiveTaskList;
	if (!soap_endpoint)
		soap_endpoint = "http://10.42.43.42:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__ReceiveTaskList.data = data;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__ReceiveTaskList(soap, &soap_tmp_ns2__ReceiveTaskList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ReceiveTaskList(soap, &soap_tmp_ns2__ReceiveTaskList, "ns2:ReceiveTaskList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ReceiveTaskList(soap, &soap_tmp_ns2__ReceiveTaskList, "ns2:ReceiveTaskList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_3)
		return soap_closesock(soap);
	soap_default_ns2__ReceiveTaskListResponse(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__ReceiveTaskListResponse(soap, _param_3, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__TaskSolve(struct soap *soap, const char *soap_endpoint, const char *soap_action, int taskId, struct ns2__soap_string *task, struct ns2__TaskSolveResponse *_param_4)
{	struct ns2__TaskSolve soap_tmp_ns2__TaskSolve;
	if (!soap_endpoint)
		soap_endpoint = "http://10.42.43.42:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__TaskSolve.taskId = taskId;
	soap_tmp_ns2__TaskSolve.task = task;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__TaskSolve(soap, &soap_tmp_ns2__TaskSolve);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__TaskSolve(soap, &soap_tmp_ns2__TaskSolve, "ns2:TaskSolve", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__TaskSolve(soap, &soap_tmp_ns2__TaskSolve, "ns2:TaskSolve", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_4)
		return soap_closesock(soap);
	soap_default_ns2__TaskSolveResponse(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns2__TaskSolveResponse(soap, _param_4, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__isBusy(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *flag)
{	struct ns2__isBusy soap_tmp_ns2__isBusy;
	struct ns2__isBusyResponse *soap_tmp_ns2__isBusyResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://10.42.43.42:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns2__isBusy(soap, &soap_tmp_ns2__isBusy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__isBusy(soap, &soap_tmp_ns2__isBusy, "ns2:isBusy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__isBusy(soap, &soap_tmp_ns2__isBusy, "ns2:isBusy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!flag)
		return soap_closesock(soap);
	soap_default_int(soap, flag);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns2__isBusyResponse = soap_get_ns2__isBusyResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (flag && soap_tmp_ns2__isBusyResponse->flag)
		*flag = *soap_tmp_ns2__isBusyResponse->flag;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns3__ReceiveTaskList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns3__data *data, struct ns3__ReceiveTaskListResponse *_param_5)
{	struct ns3__ReceiveTaskList soap_tmp_ns3__ReceiveTaskList;
	if (!soap_endpoint)
		soap_endpoint = "http://59.66.185.77:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns3__ReceiveTaskList.data = data;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns3__ReceiveTaskList(soap, &soap_tmp_ns3__ReceiveTaskList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns3__ReceiveTaskList(soap, &soap_tmp_ns3__ReceiveTaskList, "ns3:ReceiveTaskList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns3__ReceiveTaskList(soap, &soap_tmp_ns3__ReceiveTaskList, "ns3:ReceiveTaskList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_5)
		return soap_closesock(soap);
	soap_default_ns3__ReceiveTaskListResponse(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns3__ReceiveTaskListResponse(soap, _param_5, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns3__TaskSolve(struct soap *soap, const char *soap_endpoint, const char *soap_action, int taskId, struct ns3__soap_string *task, struct ns3__TaskSolveResponse *_param_6)
{	struct ns3__TaskSolve soap_tmp_ns3__TaskSolve;
	if (!soap_endpoint)
		soap_endpoint = "http://59.66.185.77:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns3__TaskSolve.taskId = taskId;
	soap_tmp_ns3__TaskSolve.task = task;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns3__TaskSolve(soap, &soap_tmp_ns3__TaskSolve);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns3__TaskSolve(soap, &soap_tmp_ns3__TaskSolve, "ns3:TaskSolve", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns3__TaskSolve(soap, &soap_tmp_ns3__TaskSolve, "ns3:TaskSolve", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_6)
		return soap_closesock(soap);
	soap_default_ns3__TaskSolveResponse(soap, _param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns3__TaskSolveResponse(soap, _param_6, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns3__isBusy(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *flag)
{	struct ns3__isBusy soap_tmp_ns3__isBusy;
	struct ns3__isBusyResponse *soap_tmp_ns3__isBusyResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://59.66.185.77:8080/";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns3__isBusy(soap, &soap_tmp_ns3__isBusy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns3__isBusy(soap, &soap_tmp_ns3__isBusy, "ns3:isBusy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns3__isBusy(soap, &soap_tmp_ns3__isBusy, "ns3:isBusy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!flag)
		return soap_closesock(soap);
	soap_default_int(soap, flag);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns3__isBusyResponse = soap_get_ns3__isBusyResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (flag && soap_tmp_ns3__isBusyResponse->flag)
		*flag = *soap_tmp_ns3__isBusyResponse->flag;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
