/* soapH.h
   Generated by gSOAP 2.8.3 from addclient.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_begin_send(soap) || soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_begin_send(soap) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE_ns3__isBusy
#define SOAP_TYPE_ns3__isBusy (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__isBusy(struct soap*, struct ns3__isBusy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__isBusy(struct soap*, const struct ns3__isBusy *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__isBusy(struct soap*, const char*, int, const struct ns3__isBusy *, const char*);
SOAP_FMAC3 struct ns3__isBusy * SOAP_FMAC4 soap_in_ns3__isBusy(struct soap*, const char*, struct ns3__isBusy *, const char*);

#ifndef soap_write_ns3__isBusy
#define soap_write_ns3__isBusy(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__isBusy(soap, data), 0) || soap_put_ns3__isBusy(soap, data, "ns3:isBusy", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__isBusy(struct soap*, const struct ns3__isBusy *, const char*, const char*);

#ifndef soap_read_ns3__isBusy
#define soap_read_ns3__isBusy(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__isBusy(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__isBusy * SOAP_FMAC4 soap_get_ns3__isBusy(struct soap*, struct ns3__isBusy *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__isBusyResponse
#define SOAP_TYPE_ns3__isBusyResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__isBusyResponse(struct soap*, struct ns3__isBusyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__isBusyResponse(struct soap*, const struct ns3__isBusyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__isBusyResponse(struct soap*, const char*, int, const struct ns3__isBusyResponse *, const char*);
SOAP_FMAC3 struct ns3__isBusyResponse * SOAP_FMAC4 soap_in_ns3__isBusyResponse(struct soap*, const char*, struct ns3__isBusyResponse *, const char*);

#ifndef soap_write_ns3__isBusyResponse
#define soap_write_ns3__isBusyResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__isBusyResponse(soap, data), 0) || soap_put_ns3__isBusyResponse(soap, data, "ns3:isBusyResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__isBusyResponse(struct soap*, const struct ns3__isBusyResponse *, const char*, const char*);

#ifndef soap_read_ns3__isBusyResponse
#define soap_read_ns3__isBusyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__isBusyResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__isBusyResponse * SOAP_FMAC4 soap_get_ns3__isBusyResponse(struct soap*, struct ns3__isBusyResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__TaskSolve
#define SOAP_TYPE_ns3__TaskSolve (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__TaskSolve(struct soap*, struct ns3__TaskSolve *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__TaskSolve(struct soap*, const struct ns3__TaskSolve *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__TaskSolve(struct soap*, const char*, int, const struct ns3__TaskSolve *, const char*);
SOAP_FMAC3 struct ns3__TaskSolve * SOAP_FMAC4 soap_in_ns3__TaskSolve(struct soap*, const char*, struct ns3__TaskSolve *, const char*);

#ifndef soap_write_ns3__TaskSolve
#define soap_write_ns3__TaskSolve(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__TaskSolve(soap, data), 0) || soap_put_ns3__TaskSolve(soap, data, "ns3:TaskSolve", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__TaskSolve(struct soap*, const struct ns3__TaskSolve *, const char*, const char*);

#ifndef soap_read_ns3__TaskSolve
#define soap_read_ns3__TaskSolve(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__TaskSolve(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__TaskSolve * SOAP_FMAC4 soap_get_ns3__TaskSolve(struct soap*, struct ns3__TaskSolve *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__TaskSolveResponse
#define SOAP_TYPE_ns3__TaskSolveResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__TaskSolveResponse(struct soap*, struct ns3__TaskSolveResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__TaskSolveResponse(struct soap*, const struct ns3__TaskSolveResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__TaskSolveResponse(struct soap*, const char*, int, const struct ns3__TaskSolveResponse *, const char*);
SOAP_FMAC3 struct ns3__TaskSolveResponse * SOAP_FMAC4 soap_in_ns3__TaskSolveResponse(struct soap*, const char*, struct ns3__TaskSolveResponse *, const char*);

#ifndef soap_write_ns3__TaskSolveResponse
#define soap_write_ns3__TaskSolveResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__TaskSolveResponse(soap, data), 0) || soap_put_ns3__TaskSolveResponse(soap, data, "ns3:TaskSolveResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__TaskSolveResponse(struct soap*, const struct ns3__TaskSolveResponse *, const char*, const char*);

#ifndef soap_read_ns3__TaskSolveResponse
#define soap_read_ns3__TaskSolveResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__TaskSolveResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__TaskSolveResponse * SOAP_FMAC4 soap_get_ns3__TaskSolveResponse(struct soap*, struct ns3__TaskSolveResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__ReceiveTaskList
#define SOAP_TYPE_ns3__ReceiveTaskList (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__ReceiveTaskList(struct soap*, struct ns3__ReceiveTaskList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__ReceiveTaskList(struct soap*, const struct ns3__ReceiveTaskList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ReceiveTaskList(struct soap*, const char*, int, const struct ns3__ReceiveTaskList *, const char*);
SOAP_FMAC3 struct ns3__ReceiveTaskList * SOAP_FMAC4 soap_in_ns3__ReceiveTaskList(struct soap*, const char*, struct ns3__ReceiveTaskList *, const char*);

#ifndef soap_write_ns3__ReceiveTaskList
#define soap_write_ns3__ReceiveTaskList(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__ReceiveTaskList(soap, data), 0) || soap_put_ns3__ReceiveTaskList(soap, data, "ns3:ReceiveTaskList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__ReceiveTaskList(struct soap*, const struct ns3__ReceiveTaskList *, const char*, const char*);

#ifndef soap_read_ns3__ReceiveTaskList
#define soap_read_ns3__ReceiveTaskList(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__ReceiveTaskList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__ReceiveTaskList * SOAP_FMAC4 soap_get_ns3__ReceiveTaskList(struct soap*, struct ns3__ReceiveTaskList *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__ReceiveTaskListResponse
#define SOAP_TYPE_ns3__ReceiveTaskListResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__ReceiveTaskListResponse(struct soap*, struct ns3__ReceiveTaskListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__ReceiveTaskListResponse(struct soap*, const struct ns3__ReceiveTaskListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ReceiveTaskListResponse(struct soap*, const char*, int, const struct ns3__ReceiveTaskListResponse *, const char*);
SOAP_FMAC3 struct ns3__ReceiveTaskListResponse * SOAP_FMAC4 soap_in_ns3__ReceiveTaskListResponse(struct soap*, const char*, struct ns3__ReceiveTaskListResponse *, const char*);

#ifndef soap_write_ns3__ReceiveTaskListResponse
#define soap_write_ns3__ReceiveTaskListResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__ReceiveTaskListResponse(soap, data), 0) || soap_put_ns3__ReceiveTaskListResponse(soap, data, "ns3:ReceiveTaskListResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__ReceiveTaskListResponse(struct soap*, const struct ns3__ReceiveTaskListResponse *, const char*, const char*);

#ifndef soap_read_ns3__ReceiveTaskListResponse
#define soap_read_ns3__ReceiveTaskListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__ReceiveTaskListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__ReceiveTaskListResponse * SOAP_FMAC4 soap_get_ns3__ReceiveTaskListResponse(struct soap*, struct ns3__ReceiveTaskListResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__isBusy
#define SOAP_TYPE_ns2__isBusy (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__isBusy(struct soap*, struct ns2__isBusy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__isBusy(struct soap*, const struct ns2__isBusy *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__isBusy(struct soap*, const char*, int, const struct ns2__isBusy *, const char*);
SOAP_FMAC3 struct ns2__isBusy * SOAP_FMAC4 soap_in_ns2__isBusy(struct soap*, const char*, struct ns2__isBusy *, const char*);

#ifndef soap_write_ns2__isBusy
#define soap_write_ns2__isBusy(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__isBusy(soap, data), 0) || soap_put_ns2__isBusy(soap, data, "ns2:isBusy", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__isBusy(struct soap*, const struct ns2__isBusy *, const char*, const char*);

#ifndef soap_read_ns2__isBusy
#define soap_read_ns2__isBusy(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__isBusy(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__isBusy * SOAP_FMAC4 soap_get_ns2__isBusy(struct soap*, struct ns2__isBusy *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__isBusyResponse
#define SOAP_TYPE_ns2__isBusyResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__isBusyResponse(struct soap*, struct ns2__isBusyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__isBusyResponse(struct soap*, const struct ns2__isBusyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__isBusyResponse(struct soap*, const char*, int, const struct ns2__isBusyResponse *, const char*);
SOAP_FMAC3 struct ns2__isBusyResponse * SOAP_FMAC4 soap_in_ns2__isBusyResponse(struct soap*, const char*, struct ns2__isBusyResponse *, const char*);

#ifndef soap_write_ns2__isBusyResponse
#define soap_write_ns2__isBusyResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__isBusyResponse(soap, data), 0) || soap_put_ns2__isBusyResponse(soap, data, "ns2:isBusyResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__isBusyResponse(struct soap*, const struct ns2__isBusyResponse *, const char*, const char*);

#ifndef soap_read_ns2__isBusyResponse
#define soap_read_ns2__isBusyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__isBusyResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__isBusyResponse * SOAP_FMAC4 soap_get_ns2__isBusyResponse(struct soap*, struct ns2__isBusyResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__TaskSolve
#define SOAP_TYPE_ns2__TaskSolve (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__TaskSolve(struct soap*, struct ns2__TaskSolve *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__TaskSolve(struct soap*, const struct ns2__TaskSolve *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__TaskSolve(struct soap*, const char*, int, const struct ns2__TaskSolve *, const char*);
SOAP_FMAC3 struct ns2__TaskSolve * SOAP_FMAC4 soap_in_ns2__TaskSolve(struct soap*, const char*, struct ns2__TaskSolve *, const char*);

#ifndef soap_write_ns2__TaskSolve
#define soap_write_ns2__TaskSolve(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__TaskSolve(soap, data), 0) || soap_put_ns2__TaskSolve(soap, data, "ns2:TaskSolve", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__TaskSolve(struct soap*, const struct ns2__TaskSolve *, const char*, const char*);

#ifndef soap_read_ns2__TaskSolve
#define soap_read_ns2__TaskSolve(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__TaskSolve(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__TaskSolve * SOAP_FMAC4 soap_get_ns2__TaskSolve(struct soap*, struct ns2__TaskSolve *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__TaskSolveResponse
#define SOAP_TYPE_ns2__TaskSolveResponse (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__TaskSolveResponse(struct soap*, struct ns2__TaskSolveResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__TaskSolveResponse(struct soap*, const struct ns2__TaskSolveResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__TaskSolveResponse(struct soap*, const char*, int, const struct ns2__TaskSolveResponse *, const char*);
SOAP_FMAC3 struct ns2__TaskSolveResponse * SOAP_FMAC4 soap_in_ns2__TaskSolveResponse(struct soap*, const char*, struct ns2__TaskSolveResponse *, const char*);

#ifndef soap_write_ns2__TaskSolveResponse
#define soap_write_ns2__TaskSolveResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__TaskSolveResponse(soap, data), 0) || soap_put_ns2__TaskSolveResponse(soap, data, "ns2:TaskSolveResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__TaskSolveResponse(struct soap*, const struct ns2__TaskSolveResponse *, const char*, const char*);

#ifndef soap_read_ns2__TaskSolveResponse
#define soap_read_ns2__TaskSolveResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__TaskSolveResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__TaskSolveResponse * SOAP_FMAC4 soap_get_ns2__TaskSolveResponse(struct soap*, struct ns2__TaskSolveResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__ReceiveTaskList
#define SOAP_TYPE_ns2__ReceiveTaskList (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ReceiveTaskList(struct soap*, struct ns2__ReceiveTaskList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ReceiveTaskList(struct soap*, const struct ns2__ReceiveTaskList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ReceiveTaskList(struct soap*, const char*, int, const struct ns2__ReceiveTaskList *, const char*);
SOAP_FMAC3 struct ns2__ReceiveTaskList * SOAP_FMAC4 soap_in_ns2__ReceiveTaskList(struct soap*, const char*, struct ns2__ReceiveTaskList *, const char*);

#ifndef soap_write_ns2__ReceiveTaskList
#define soap_write_ns2__ReceiveTaskList(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__ReceiveTaskList(soap, data), 0) || soap_put_ns2__ReceiveTaskList(soap, data, "ns2:ReceiveTaskList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ReceiveTaskList(struct soap*, const struct ns2__ReceiveTaskList *, const char*, const char*);

#ifndef soap_read_ns2__ReceiveTaskList
#define soap_read_ns2__ReceiveTaskList(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__ReceiveTaskList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__ReceiveTaskList * SOAP_FMAC4 soap_get_ns2__ReceiveTaskList(struct soap*, struct ns2__ReceiveTaskList *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__ReceiveTaskListResponse
#define SOAP_TYPE_ns2__ReceiveTaskListResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ReceiveTaskListResponse(struct soap*, struct ns2__ReceiveTaskListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ReceiveTaskListResponse(struct soap*, const struct ns2__ReceiveTaskListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ReceiveTaskListResponse(struct soap*, const char*, int, const struct ns2__ReceiveTaskListResponse *, const char*);
SOAP_FMAC3 struct ns2__ReceiveTaskListResponse * SOAP_FMAC4 soap_in_ns2__ReceiveTaskListResponse(struct soap*, const char*, struct ns2__ReceiveTaskListResponse *, const char*);

#ifndef soap_write_ns2__ReceiveTaskListResponse
#define soap_write_ns2__ReceiveTaskListResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__ReceiveTaskListResponse(soap, data), 0) || soap_put_ns2__ReceiveTaskListResponse(soap, data, "ns2:ReceiveTaskListResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ReceiveTaskListResponse(struct soap*, const struct ns2__ReceiveTaskListResponse *, const char*, const char*);

#ifndef soap_read_ns2__ReceiveTaskListResponse
#define soap_read_ns2__ReceiveTaskListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__ReceiveTaskListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__ReceiveTaskListResponse * SOAP_FMAC4 soap_get_ns2__ReceiveTaskListResponse(struct soap*, struct ns2__ReceiveTaskListResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__isBusy
#define SOAP_TYPE_ns1__isBusy (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__isBusy(struct soap*, struct ns1__isBusy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__isBusy(struct soap*, const struct ns1__isBusy *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__isBusy(struct soap*, const char*, int, const struct ns1__isBusy *, const char*);
SOAP_FMAC3 struct ns1__isBusy * SOAP_FMAC4 soap_in_ns1__isBusy(struct soap*, const char*, struct ns1__isBusy *, const char*);

#ifndef soap_write_ns1__isBusy
#define soap_write_ns1__isBusy(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__isBusy(soap, data), 0) || soap_put_ns1__isBusy(soap, data, "ns1:isBusy", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__isBusy(struct soap*, const struct ns1__isBusy *, const char*, const char*);

#ifndef soap_read_ns1__isBusy
#define soap_read_ns1__isBusy(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__isBusy(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__isBusy * SOAP_FMAC4 soap_get_ns1__isBusy(struct soap*, struct ns1__isBusy *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__isBusyResponse
#define SOAP_TYPE_ns1__isBusyResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__isBusyResponse(struct soap*, struct ns1__isBusyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__isBusyResponse(struct soap*, const struct ns1__isBusyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__isBusyResponse(struct soap*, const char*, int, const struct ns1__isBusyResponse *, const char*);
SOAP_FMAC3 struct ns1__isBusyResponse * SOAP_FMAC4 soap_in_ns1__isBusyResponse(struct soap*, const char*, struct ns1__isBusyResponse *, const char*);

#ifndef soap_write_ns1__isBusyResponse
#define soap_write_ns1__isBusyResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__isBusyResponse(soap, data), 0) || soap_put_ns1__isBusyResponse(soap, data, "ns1:isBusyResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__isBusyResponse(struct soap*, const struct ns1__isBusyResponse *, const char*, const char*);

#ifndef soap_read_ns1__isBusyResponse
#define soap_read_ns1__isBusyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__isBusyResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__isBusyResponse * SOAP_FMAC4 soap_get_ns1__isBusyResponse(struct soap*, struct ns1__isBusyResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__TaskSolve
#define SOAP_TYPE_ns1__TaskSolve (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__TaskSolve(struct soap*, struct ns1__TaskSolve *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__TaskSolve(struct soap*, const struct ns1__TaskSolve *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__TaskSolve(struct soap*, const char*, int, const struct ns1__TaskSolve *, const char*);
SOAP_FMAC3 struct ns1__TaskSolve * SOAP_FMAC4 soap_in_ns1__TaskSolve(struct soap*, const char*, struct ns1__TaskSolve *, const char*);

#ifndef soap_write_ns1__TaskSolve
#define soap_write_ns1__TaskSolve(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__TaskSolve(soap, data), 0) || soap_put_ns1__TaskSolve(soap, data, "ns1:TaskSolve", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__TaskSolve(struct soap*, const struct ns1__TaskSolve *, const char*, const char*);

#ifndef soap_read_ns1__TaskSolve
#define soap_read_ns1__TaskSolve(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__TaskSolve(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__TaskSolve * SOAP_FMAC4 soap_get_ns1__TaskSolve(struct soap*, struct ns1__TaskSolve *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__TaskSolveResponse
#define SOAP_TYPE_ns1__TaskSolveResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__TaskSolveResponse(struct soap*, struct ns1__TaskSolveResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__TaskSolveResponse(struct soap*, const struct ns1__TaskSolveResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__TaskSolveResponse(struct soap*, const char*, int, const struct ns1__TaskSolveResponse *, const char*);
SOAP_FMAC3 struct ns1__TaskSolveResponse * SOAP_FMAC4 soap_in_ns1__TaskSolveResponse(struct soap*, const char*, struct ns1__TaskSolveResponse *, const char*);

#ifndef soap_write_ns1__TaskSolveResponse
#define soap_write_ns1__TaskSolveResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__TaskSolveResponse(soap, data), 0) || soap_put_ns1__TaskSolveResponse(soap, data, "ns1:TaskSolveResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__TaskSolveResponse(struct soap*, const struct ns1__TaskSolveResponse *, const char*, const char*);

#ifndef soap_read_ns1__TaskSolveResponse
#define soap_read_ns1__TaskSolveResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__TaskSolveResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__TaskSolveResponse * SOAP_FMAC4 soap_get_ns1__TaskSolveResponse(struct soap*, struct ns1__TaskSolveResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ReceiveTaskList
#define SOAP_TYPE_ns1__ReceiveTaskList (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ReceiveTaskList(struct soap*, struct ns1__ReceiveTaskList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ReceiveTaskList(struct soap*, const struct ns1__ReceiveTaskList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ReceiveTaskList(struct soap*, const char*, int, const struct ns1__ReceiveTaskList *, const char*);
SOAP_FMAC3 struct ns1__ReceiveTaskList * SOAP_FMAC4 soap_in_ns1__ReceiveTaskList(struct soap*, const char*, struct ns1__ReceiveTaskList *, const char*);

#ifndef soap_write_ns1__ReceiveTaskList
#define soap_write_ns1__ReceiveTaskList(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ReceiveTaskList(soap, data), 0) || soap_put_ns1__ReceiveTaskList(soap, data, "ns1:ReceiveTaskList", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ReceiveTaskList(struct soap*, const struct ns1__ReceiveTaskList *, const char*, const char*);

#ifndef soap_read_ns1__ReceiveTaskList
#define soap_read_ns1__ReceiveTaskList(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ReceiveTaskList(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ReceiveTaskList * SOAP_FMAC4 soap_get_ns1__ReceiveTaskList(struct soap*, struct ns1__ReceiveTaskList *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ReceiveTaskListResponse
#define SOAP_TYPE_ns1__ReceiveTaskListResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ReceiveTaskListResponse(struct soap*, struct ns1__ReceiveTaskListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ReceiveTaskListResponse(struct soap*, const struct ns1__ReceiveTaskListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ReceiveTaskListResponse(struct soap*, const char*, int, const struct ns1__ReceiveTaskListResponse *, const char*);
SOAP_FMAC3 struct ns1__ReceiveTaskListResponse * SOAP_FMAC4 soap_in_ns1__ReceiveTaskListResponse(struct soap*, const char*, struct ns1__ReceiveTaskListResponse *, const char*);

#ifndef soap_write_ns1__ReceiveTaskListResponse
#define soap_write_ns1__ReceiveTaskListResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ReceiveTaskListResponse(soap, data), 0) || soap_put_ns1__ReceiveTaskListResponse(soap, data, "ns1:ReceiveTaskListResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ReceiveTaskListResponse(struct soap*, const struct ns1__ReceiveTaskListResponse *, const char*, const char*);

#ifndef soap_read_ns1__ReceiveTaskListResponse
#define soap_read_ns1__ReceiveTaskListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ReceiveTaskListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ReceiveTaskListResponse * SOAP_FMAC4 soap_get_ns1__ReceiveTaskListResponse(struct soap*, struct ns1__ReceiveTaskListResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__data
#define SOAP_TYPE_ns3__data (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__data(struct soap*, struct ns3__data *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__data(struct soap*, const struct ns3__data *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__data(struct soap*, const char*, int, const struct ns3__data *, const char*);
SOAP_FMAC3 struct ns3__data * SOAP_FMAC4 soap_in_ns3__data(struct soap*, const char*, struct ns3__data *, const char*);

#ifndef soap_write_ns3__data
#define soap_write_ns3__data(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__data(soap, data), 0) || soap_put_ns3__data(soap, data, "ns3:data", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__data(struct soap*, const struct ns3__data *, const char*, const char*);

#ifndef soap_read_ns3__data
#define soap_read_ns3__data(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__data(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__data * SOAP_FMAC4 soap_get_ns3__data(struct soap*, struct ns3__data *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__data
#define SOAP_TYPE_ns2__data (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__data(struct soap*, struct ns2__data *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__data(struct soap*, const struct ns2__data *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__data(struct soap*, const char*, int, const struct ns2__data *, const char*);
SOAP_FMAC3 struct ns2__data * SOAP_FMAC4 soap_in_ns2__data(struct soap*, const char*, struct ns2__data *, const char*);

#ifndef soap_write_ns2__data
#define soap_write_ns2__data(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__data(soap, data), 0) || soap_put_ns2__data(soap, data, "ns2:data", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__data(struct soap*, const struct ns2__data *, const char*, const char*);

#ifndef soap_read_ns2__data
#define soap_read_ns2__data(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__data(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__data * SOAP_FMAC4 soap_get_ns2__data(struct soap*, struct ns2__data *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__data
#define SOAP_TYPE_ns1__data (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__data(struct soap*, struct ns1__data *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__data(struct soap*, const struct ns1__data *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__data(struct soap*, const char*, int, const struct ns1__data *, const char*);
SOAP_FMAC3 struct ns1__data * SOAP_FMAC4 soap_in_ns1__data(struct soap*, const char*, struct ns1__data *, const char*);

#ifndef soap_write_ns1__data
#define soap_write_ns1__data(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__data(soap, data), 0) || soap_put_ns1__data(soap, data, "ns1:data", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__data(struct soap*, const struct ns1__data *, const char*, const char*);

#ifndef soap_read_ns1__data
#define soap_read_ns1__data(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__data(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__data * SOAP_FMAC4 soap_get_ns1__data(struct soap*, struct ns1__data *, const char*, const char*);

#ifndef SOAP_TYPE_ns3__soap_string
#define SOAP_TYPE_ns3__soap_string (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__soap_string(struct soap*, struct ns3__soap_string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__soap_string(struct soap*, const struct ns3__soap_string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__soap_string(struct soap*, const char*, int, const struct ns3__soap_string *, const char*);
SOAP_FMAC3 struct ns3__soap_string * SOAP_FMAC4 soap_in_ns3__soap_string(struct soap*, const char*, struct ns3__soap_string *, const char*);

#ifndef soap_write_ns3__soap_string
#define soap_write_ns3__soap_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns3__soap_string(soap, data), 0) || soap_put_ns3__soap_string(soap, data, "ns3:soap-string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__soap_string(struct soap*, const struct ns3__soap_string *, const char*, const char*);

#ifndef soap_read_ns3__soap_string
#define soap_read_ns3__soap_string(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__soap_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__soap_string * SOAP_FMAC4 soap_get_ns3__soap_string(struct soap*, struct ns3__soap_string *, const char*, const char*);

#ifndef SOAP_TYPE_ns2__soap_string
#define SOAP_TYPE_ns2__soap_string (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__soap_string(struct soap*, struct ns2__soap_string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__soap_string(struct soap*, const struct ns2__soap_string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__soap_string(struct soap*, const char*, int, const struct ns2__soap_string *, const char*);
SOAP_FMAC3 struct ns2__soap_string * SOAP_FMAC4 soap_in_ns2__soap_string(struct soap*, const char*, struct ns2__soap_string *, const char*);

#ifndef soap_write_ns2__soap_string
#define soap_write_ns2__soap_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns2__soap_string(soap, data), 0) || soap_put_ns2__soap_string(soap, data, "ns2:soap-string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__soap_string(struct soap*, const struct ns2__soap_string *, const char*, const char*);

#ifndef soap_read_ns2__soap_string
#define soap_read_ns2__soap_string(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__soap_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__soap_string * SOAP_FMAC4 soap_get_ns2__soap_string(struct soap*, struct ns2__soap_string *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__soap_string
#define SOAP_TYPE_ns1__soap_string (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__soap_string(struct soap*, struct ns1__soap_string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__soap_string(struct soap*, const struct ns1__soap_string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__soap_string(struct soap*, const char*, int, const struct ns1__soap_string *, const char*);
SOAP_FMAC3 struct ns1__soap_string * SOAP_FMAC4 soap_in_ns1__soap_string(struct soap*, const char*, struct ns1__soap_string *, const char*);

#ifndef soap_write_ns1__soap_string
#define soap_write_ns1__soap_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__soap_string(soap, data), 0) || soap_put_ns1__soap_string(soap, data, "ns1:soap-string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__soap_string(struct soap*, const struct ns1__soap_string *, const char*, const char*);

#ifndef soap_read_ns1__soap_string
#define soap_read_ns1__soap_string(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__soap_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__soap_string * SOAP_FMAC4 soap_get_ns1__soap_string(struct soap*, struct ns1__soap_string *, const char*, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef soap_write_xsd__base64Binary
#define soap_write_xsd__base64Binary(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__base64Binary(soap, data), 0) || soap_put_xsd__base64Binary(soap, data, "xsd:base64Binary", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);

#ifndef soap_read_xsd__base64Binary
#define soap_read_xsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons3__TaskSolveResponse
#define SOAP_TYPE_PointerTons3__TaskSolveResponse (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__TaskSolveResponse(struct soap*, struct ns3__TaskSolveResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__TaskSolveResponse(struct soap*, const char *, int, struct ns3__TaskSolveResponse *const*, const char *);
SOAP_FMAC3 struct ns3__TaskSolveResponse ** SOAP_FMAC4 soap_in_PointerTons3__TaskSolveResponse(struct soap*, const char*, struct ns3__TaskSolveResponse **, const char*);

#ifndef soap_write_PointerTons3__TaskSolveResponse
#define soap_write_PointerTons3__TaskSolveResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__TaskSolveResponse(soap, data), 0) || soap_put_PointerTons3__TaskSolveResponse(soap, data, "ns3:TaskSolveResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__TaskSolveResponse(struct soap*, struct ns3__TaskSolveResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons3__TaskSolveResponse
#define soap_read_PointerTons3__TaskSolveResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__TaskSolveResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__TaskSolveResponse ** SOAP_FMAC4 soap_get_PointerTons3__TaskSolveResponse(struct soap*, struct ns3__TaskSolveResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__ReceiveTaskListResponse
#define SOAP_TYPE_PointerTons3__ReceiveTaskListResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ReceiveTaskListResponse(struct soap*, struct ns3__ReceiveTaskListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ReceiveTaskListResponse(struct soap*, const char *, int, struct ns3__ReceiveTaskListResponse *const*, const char *);
SOAP_FMAC3 struct ns3__ReceiveTaskListResponse ** SOAP_FMAC4 soap_in_PointerTons3__ReceiveTaskListResponse(struct soap*, const char*, struct ns3__ReceiveTaskListResponse **, const char*);

#ifndef soap_write_PointerTons3__ReceiveTaskListResponse
#define soap_write_PointerTons3__ReceiveTaskListResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__ReceiveTaskListResponse(soap, data), 0) || soap_put_PointerTons3__ReceiveTaskListResponse(soap, data, "ns3:ReceiveTaskListResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ReceiveTaskListResponse(struct soap*, struct ns3__ReceiveTaskListResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons3__ReceiveTaskListResponse
#define soap_read_PointerTons3__ReceiveTaskListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__ReceiveTaskListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__ReceiveTaskListResponse ** SOAP_FMAC4 soap_get_PointerTons3__ReceiveTaskListResponse(struct soap*, struct ns3__ReceiveTaskListResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__data
#define SOAP_TYPE_PointerTons3__data (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__data(struct soap*, struct ns3__data *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__data(struct soap*, const char *, int, struct ns3__data *const*, const char *);
SOAP_FMAC3 struct ns3__data ** SOAP_FMAC4 soap_in_PointerTons3__data(struct soap*, const char*, struct ns3__data **, const char*);

#ifndef soap_write_PointerTons3__data
#define soap_write_PointerTons3__data(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__data(soap, data), 0) || soap_put_PointerTons3__data(soap, data, "ns3:data", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__data(struct soap*, struct ns3__data *const*, const char*, const char*);

#ifndef soap_read_PointerTons3__data
#define soap_read_PointerTons3__data(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__data(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__data ** SOAP_FMAC4 soap_get_PointerTons3__data(struct soap*, struct ns3__data **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons3__soap_string
#define SOAP_TYPE_PointerTons3__soap_string (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__soap_string(struct soap*, struct ns3__soap_string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__soap_string(struct soap*, const char *, int, struct ns3__soap_string *const*, const char *);
SOAP_FMAC3 struct ns3__soap_string ** SOAP_FMAC4 soap_in_PointerTons3__soap_string(struct soap*, const char*, struct ns3__soap_string **, const char*);

#ifndef soap_write_PointerTons3__soap_string
#define soap_write_PointerTons3__soap_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons3__soap_string(soap, data), 0) || soap_put_PointerTons3__soap_string(soap, data, "ns3:soap-string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__soap_string(struct soap*, struct ns3__soap_string *const*, const char*, const char*);

#ifndef soap_read_PointerTons3__soap_string
#define soap_read_PointerTons3__soap_string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__soap_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns3__soap_string ** SOAP_FMAC4 soap_get_PointerTons3__soap_string(struct soap*, struct ns3__soap_string **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__TaskSolveResponse
#define SOAP_TYPE_PointerTons2__TaskSolveResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__TaskSolveResponse(struct soap*, struct ns2__TaskSolveResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__TaskSolveResponse(struct soap*, const char *, int, struct ns2__TaskSolveResponse *const*, const char *);
SOAP_FMAC3 struct ns2__TaskSolveResponse ** SOAP_FMAC4 soap_in_PointerTons2__TaskSolveResponse(struct soap*, const char*, struct ns2__TaskSolveResponse **, const char*);

#ifndef soap_write_PointerTons2__TaskSolveResponse
#define soap_write_PointerTons2__TaskSolveResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__TaskSolveResponse(soap, data), 0) || soap_put_PointerTons2__TaskSolveResponse(soap, data, "ns2:TaskSolveResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__TaskSolveResponse(struct soap*, struct ns2__TaskSolveResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__TaskSolveResponse
#define soap_read_PointerTons2__TaskSolveResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__TaskSolveResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__TaskSolveResponse ** SOAP_FMAC4 soap_get_PointerTons2__TaskSolveResponse(struct soap*, struct ns2__TaskSolveResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__ReceiveTaskListResponse
#define SOAP_TYPE_PointerTons2__ReceiveTaskListResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__ReceiveTaskListResponse(struct soap*, struct ns2__ReceiveTaskListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__ReceiveTaskListResponse(struct soap*, const char *, int, struct ns2__ReceiveTaskListResponse *const*, const char *);
SOAP_FMAC3 struct ns2__ReceiveTaskListResponse ** SOAP_FMAC4 soap_in_PointerTons2__ReceiveTaskListResponse(struct soap*, const char*, struct ns2__ReceiveTaskListResponse **, const char*);

#ifndef soap_write_PointerTons2__ReceiveTaskListResponse
#define soap_write_PointerTons2__ReceiveTaskListResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__ReceiveTaskListResponse(soap, data), 0) || soap_put_PointerTons2__ReceiveTaskListResponse(soap, data, "ns2:ReceiveTaskListResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__ReceiveTaskListResponse(struct soap*, struct ns2__ReceiveTaskListResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__ReceiveTaskListResponse
#define soap_read_PointerTons2__ReceiveTaskListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__ReceiveTaskListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__ReceiveTaskListResponse ** SOAP_FMAC4 soap_get_PointerTons2__ReceiveTaskListResponse(struct soap*, struct ns2__ReceiveTaskListResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__data
#define SOAP_TYPE_PointerTons2__data (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__data(struct soap*, struct ns2__data *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__data(struct soap*, const char *, int, struct ns2__data *const*, const char *);
SOAP_FMAC3 struct ns2__data ** SOAP_FMAC4 soap_in_PointerTons2__data(struct soap*, const char*, struct ns2__data **, const char*);

#ifndef soap_write_PointerTons2__data
#define soap_write_PointerTons2__data(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__data(soap, data), 0) || soap_put_PointerTons2__data(soap, data, "ns2:data", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__data(struct soap*, struct ns2__data *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__data
#define soap_read_PointerTons2__data(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__data(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__data ** SOAP_FMAC4 soap_get_PointerTons2__data(struct soap*, struct ns2__data **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons2__soap_string
#define SOAP_TYPE_PointerTons2__soap_string (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__soap_string(struct soap*, struct ns2__soap_string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__soap_string(struct soap*, const char *, int, struct ns2__soap_string *const*, const char *);
SOAP_FMAC3 struct ns2__soap_string ** SOAP_FMAC4 soap_in_PointerTons2__soap_string(struct soap*, const char*, struct ns2__soap_string **, const char*);

#ifndef soap_write_PointerTons2__soap_string
#define soap_write_PointerTons2__soap_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons2__soap_string(soap, data), 0) || soap_put_PointerTons2__soap_string(soap, data, "ns2:soap-string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__soap_string(struct soap*, struct ns2__soap_string *const*, const char*, const char*);

#ifndef soap_read_PointerTons2__soap_string
#define soap_read_PointerTons2__soap_string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__soap_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns2__soap_string ** SOAP_FMAC4 soap_get_PointerTons2__soap_string(struct soap*, struct ns2__soap_string **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data), 0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__TaskSolveResponse
#define SOAP_TYPE_PointerTons1__TaskSolveResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__TaskSolveResponse(struct soap*, struct ns1__TaskSolveResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__TaskSolveResponse(struct soap*, const char *, int, struct ns1__TaskSolveResponse *const*, const char *);
SOAP_FMAC3 struct ns1__TaskSolveResponse ** SOAP_FMAC4 soap_in_PointerTons1__TaskSolveResponse(struct soap*, const char*, struct ns1__TaskSolveResponse **, const char*);

#ifndef soap_write_PointerTons1__TaskSolveResponse
#define soap_write_PointerTons1__TaskSolveResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__TaskSolveResponse(soap, data), 0) || soap_put_PointerTons1__TaskSolveResponse(soap, data, "ns1:TaskSolveResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__TaskSolveResponse(struct soap*, struct ns1__TaskSolveResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__TaskSolveResponse
#define soap_read_PointerTons1__TaskSolveResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__TaskSolveResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__TaskSolveResponse ** SOAP_FMAC4 soap_get_PointerTons1__TaskSolveResponse(struct soap*, struct ns1__TaskSolveResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ReceiveTaskListResponse
#define SOAP_TYPE_PointerTons1__ReceiveTaskListResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ReceiveTaskListResponse(struct soap*, struct ns1__ReceiveTaskListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ReceiveTaskListResponse(struct soap*, const char *, int, struct ns1__ReceiveTaskListResponse *const*, const char *);
SOAP_FMAC3 struct ns1__ReceiveTaskListResponse ** SOAP_FMAC4 soap_in_PointerTons1__ReceiveTaskListResponse(struct soap*, const char*, struct ns1__ReceiveTaskListResponse **, const char*);

#ifndef soap_write_PointerTons1__ReceiveTaskListResponse
#define soap_write_PointerTons1__ReceiveTaskListResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ReceiveTaskListResponse(soap, data), 0) || soap_put_PointerTons1__ReceiveTaskListResponse(soap, data, "ns1:ReceiveTaskListResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ReceiveTaskListResponse(struct soap*, struct ns1__ReceiveTaskListResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ReceiveTaskListResponse
#define soap_read_PointerTons1__ReceiveTaskListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ReceiveTaskListResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ReceiveTaskListResponse ** SOAP_FMAC4 soap_get_PointerTons1__ReceiveTaskListResponse(struct soap*, struct ns1__ReceiveTaskListResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__data
#define SOAP_TYPE_PointerTons1__data (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__data(struct soap*, struct ns1__data *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__data(struct soap*, const char *, int, struct ns1__data *const*, const char *);
SOAP_FMAC3 struct ns1__data ** SOAP_FMAC4 soap_in_PointerTons1__data(struct soap*, const char*, struct ns1__data **, const char*);

#ifndef soap_write_PointerTons1__data
#define soap_write_PointerTons1__data(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__data(soap, data), 0) || soap_put_PointerTons1__data(soap, data, "ns1:data", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__data(struct soap*, struct ns1__data *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__data
#define soap_read_PointerTons1__data(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__data(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__data ** SOAP_FMAC4 soap_get_PointerTons1__data(struct soap*, struct ns1__data **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__soap_string
#define SOAP_TYPE_PointerTons1__soap_string (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__soap_string(struct soap*, struct ns1__soap_string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__soap_string(struct soap*, const char *, int, struct ns1__soap_string *const*, const char *);
SOAP_FMAC3 struct ns1__soap_string ** SOAP_FMAC4 soap_in_PointerTons1__soap_string(struct soap*, const char*, struct ns1__soap_string **, const char*);

#ifndef soap_write_PointerTons1__soap_string
#define soap_write_PointerTons1__soap_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__soap_string(soap, data), 0) || soap_put_PointerTons1__soap_string(soap, data, "ns1:soap-string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__soap_string(struct soap*, struct ns1__soap_string *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__soap_string
#define soap_read_PointerTons1__soap_string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__soap_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__soap_string ** SOAP_FMAC4 soap_get_PointerTons1__soap_string(struct soap*, struct ns1__soap_string **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef soap_write_PointerTounsignedByte
#define soap_write_PointerTounsignedByte(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTounsignedByte(soap, data), 0) || soap_put_PointerTounsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);

#ifndef soap_read_PointerTounsignedByte
#define soap_read_PointerTounsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (7)
#endif

#define soap_default_xsd__anyURI(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__anyURI(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef soap_write_xsd__anyURI
#define soap_write_xsd__anyURI(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__anyURI(soap, data), 0) || soap_put_xsd__anyURI(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_xsd__anyURI
#define soap_read_xsd__anyURI(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__anyURI(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
